-- MySQL Script generated by MySQL Workbench
-- Sat Jul  1 08:45:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SimoneJoias
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SimoneJoias` ;

-- -----------------------------------------------------
-- Schema SimoneJoias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SimoneJoias` DEFAULT CHARACTER SET utf8 ;
USE `SimoneJoias` ;

-- -----------------------------------------------------
-- Table `SimoneJoias`.`Funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SimoneJoias`.`Funcionarios` ;

CREATE TABLE IF NOT EXISTS `SimoneJoias`.`Funcionarios` (
  `idFuncionario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Usuario` VARCHAR(250) NOT NULL,
  `Senha` VARCHAR(250) NOT NULL,
  `isAdm` TINYINT NOT NULL,
  `Data_de_cadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SimoneJoias`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SimoneJoias`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `SimoneJoias`.`Clientes` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(250) NOT NULL,
  `data_de_nascimento` DATE NULL,
  `Endereço` VARCHAR(250) NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `Celular` VARCHAR(15) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(250) NULL,
  `Origem` VARCHAR(45) NULL,
  `Funcionario_que_cadastrou` VARCHAR(100) NULL,
  `Funcionario_idFuncionario` INT UNSIGNED NULL,
  `Data_de_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Comentario` TEXT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  INDEX `fk_Cliente_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Cliente_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `SimoneJoias`.`Funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SimoneJoias`.`Negocios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SimoneJoias`.`Negocios` ;

CREATE TABLE IF NOT EXISTS `SimoneJoias`.`Negocios` (
  `idNegocio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Funcionario` VARCHAR(100) NULL,
  `idFuncionario` INT UNSIGNED NULL,
  `Cliente` VARCHAR(100) NULL,
  `idCliente` INT UNSIGNED NULL,
  `Data_do_Negocio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Tipo_de_negocio` VARCHAR(50) NOT NULL,
  `Comentario` VARCHAR(250) NULL,
  `Valor_do_negocio` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`idNegocio`),
  INDEX `fk_Negocio_Funcionario_idx` (`idFuncionario` ASC),
  INDEX `fk_Negocio_Cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Negocio_Funcionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `SimoneJoias`.`Funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Negocio_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `SimoneJoias`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SimoneJoias`.`Lojas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SimoneJoias`.`Lojas` ;

CREATE TABLE IF NOT EXISTS `SimoneJoias`.`Lojas` (
  `idLoja` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(250) NULL,
  `Telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`idLoja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SimoneJoias`.`Lojas_has_Funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SimoneJoias`.`Lojas_has_Funcionarios` ;

CREATE TABLE IF NOT EXISTS `SimoneJoias`.`Lojas_has_Funcionarios` (
  `Lojas_idLoja` INT UNSIGNED NOT NULL,
  `Funcionarios_idFuncionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Lojas_idLoja`, `Funcionarios_idFuncionario`),
  INDEX `fk_Lojas_has_Funcionarios_Funcionarios1_idx` (`Funcionarios_idFuncionario` ASC),
  INDEX `fk_Lojas_has_Funcionarios_Lojas1_idx` (`Lojas_idLoja` ASC),
  CONSTRAINT `fk_Lojas_has_Funcionarios_Lojas1`
    FOREIGN KEY (`Lojas_idLoja`)
    REFERENCES `SimoneJoias`.`Lojas` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lojas_has_Funcionarios_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionario`)
    REFERENCES `SimoneJoias`.`Funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SimoneJoias`.`Alteraçoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SimoneJoias`.`Alteraçoes` ;

CREATE TABLE IF NOT EXISTS `SimoneJoias`.`Alteraçoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tabela` VARCHAR(45) NOT NULL,
  `valores` VARCHAR(5000) NOT NULL,
  `DATA_ALTERAÇAO` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SimoneJoias`.`Tarefas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SimoneJoias`.`Tarefas` ;

CREATE TABLE IF NOT EXISTS `SimoneJoias`.`Tarefas` (
  `idTarefas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idFuncionario_Criador` INT UNSIGNED NOT NULL,
  `idFuncionario_Delegado` INT UNSIGNED NOT NULL,
  `Data_Criaçao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Tipo_de_tarefa` VARCHAR(250) NOT NULL,
  `Data_Limite` DATE NOT NULL,
  `Comentario` TEXT NULL,
  PRIMARY KEY (`idTarefas`),
  INDEX `fk_Tarefas_Funcionarios1_idx` (`idFuncionario_Criador` ASC),
  INDEX `fk_Tarefas_Funcionarios2_idx` (`idFuncionario_Delegado` ASC),
  CONSTRAINT `fk_Tarefas_Funcionarios1`
    FOREIGN KEY (`idFuncionario_Criador`)
    REFERENCES `SimoneJoias`.`Funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tarefas_Funcionarios2`
    FOREIGN KEY (`idFuncionario_Delegado`)
    REFERENCES `SimoneJoias`.`Funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `SimoneJoias`;

DELIMITER $$

USE `SimoneJoias`$$
DROP TRIGGER IF EXISTS `SimoneJoias`.`Funcionarios_BEFORE_UPDATE` $$
USE `SimoneJoias`$$
CREATE DEFINER = CURRENT_USER TRIGGER `SimoneJoias`.`Funcionarios_BEFORE_UPDATE` BEFORE UPDATE ON `Funcionarios` FOR EACH ROW
BEGIN 
INSERT INTO `Alteraçoes` values (
default,
"Funcionarios",
concat(
OLD.idFuncionario,"|",
OLD.Nome,"|",
OLD.Usuario,"|",
OLD.Senha,"|",
OLD.isAdm),
DEFAULT);
END$$


USE `SimoneJoias`$$
DROP TRIGGER IF EXISTS `SimoneJoias`.`Clientes_BEFORE_UPDATE` $$
USE `SimoneJoias`$$
CREATE DEFINER = CURRENT_USER TRIGGER `SimoneJoias`.`Clientes_BEFORE_UPDATE` BEFORE UPDATE ON `Clientes` FOR EACH ROW
BEGIN
	
set @v = CONCAT(
    COALESCE(OLD.idCliente,''),"|",
    COALESCE(OLD.Nome,''),"|",
    COALESCE(OLD.data_de_nascimento,''),"|",
    COALESCE(OLD.Endereço,''),"|",
    COALESCE(OLD.CPF,''),"|",
    COALESCE(OLD.Celular,''),"|",
    COALESCE(OLD.Categoria,''),"|",
    COALESCE(OLD.Email,''),"|",
    COALESCE(OLD.Origem,''),"|",
    COALESCE(OLD.Funcionario_que_cadastrou,''),"|",
    COALESCE(OLD.Funcionario_idFuncionario,''),"|",
    COALESCE(OLD.Data_de_cadastro,''),"|",
    COALESCE(OLD.Comentario,''));
INSERT INTO `Alteraçoes` values (default,"Clientes",@v,
default);
END$$


USE `SimoneJoias`$$
DROP TRIGGER IF EXISTS `SimoneJoias`.`Negocios_BEFORE_UPDATE` $$
USE `SimoneJoias`$$
CREATE DEFINER = CURRENT_USER TRIGGER `SimoneJoias`.`Negocios_BEFORE_UPDATE` BEFORE UPDATE ON `Negocios` FOR EACH ROW
BEGIN
INSERT INTO `Alteraçoes` values (
default,
"Negocios",
concat(
 COALESCE(OLD.idNegocio,''),"|",
 COALESCE(OLD.Funcionario,''),"|",
 COALESCE(OLD.idFuncionario,''),"|",
 COALESCE(OLD.Cliente,''),"|",
 COALESCE(OLD.idCliente,''),"|",
 COALESCE(OLD.Data_do_Negocio,''),"|",
 COALESCE(OLD.Tipo_de_negocio,''),"|",
 COALESCE(OLD.Comentario,''),"|",
 COALESCE(OLD.Valor_do_negocio,'')),
default);
END$$


USE `SimoneJoias`$$
DROP TRIGGER IF EXISTS `SimoneJoias`.`Lojas_has_Funcionarios_AFTER_UPDATE` $$
USE `SimoneJoias`$$
CREATE DEFINER = CURRENT_USER TRIGGER `SimoneJoias`.`Lojas_has_Funcionarios_AFTER_UPDATE` AFTER UPDATE ON `Lojas_has_Funcionarios` FOR EACH ROW
BEGIN
insert into `Alteraçoes` values(default,'Loja_has_Funionarios',CONCAT(OLD.Lojas_idLoja," ",OLD.Funcionarios_idFuncionario),default);
END$$


USE `SimoneJoias`$$
DROP TRIGGER IF EXISTS `SimoneJoias`.`Tarefas_BEFORE_UPDATE` $$
USE `SimoneJoias`$$
CREATE DEFINER = CURRENT_USER TRIGGER `SimoneJoias`.`Tarefas_BEFORE_UPDATE` BEFORE UPDATE ON `Tarefas` FOR EACH ROW
BEGIN
INSERT INTO `Alteraçoes` values (
default,
"Tarefas",
concat(
OLD.idTarefas,"|",
OLD.idFuncionario_Criador,"|",
OLD.idFuncionario_Delegado,"|",
OLD.Data_Criaçao,"|",
COALESCE(OLD.Tipo_de_tarefa,''),"|",
COALESCE(OLD.Data_Limite,''),"|",
COALESCE(OLD.Comentario,'')
),
DEFAULT);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
